name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 或者你的主分支名称，比如 master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i --frozen-lockfile

      - name: Build Astro site
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Astro 的默认构建目录
